# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout_filepath_debug_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1314, 870)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget_PathsFound = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget_PathsFound.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tableWidget_PathsFound.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_PathsFound.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_PathsFound.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_PathsFound.setColumnCount(3)
        self.tableWidget_PathsFound.setObjectName("tableWidget_PathsFound")
        self.tableWidget_PathsFound.setRowCount(0)
        self.tableWidget_PathsFound.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tableWidget_PathsFound)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_OldPath = QtWidgets.QLabel(self.groupBox_3)
        self.label_OldPath.setText("")
        self.label_OldPath.setObjectName("label_OldPath")
        self.verticalLayout_3.addWidget(self.label_OldPath)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_NewPath = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_NewPath.setObjectName("lineEdit_NewPath")
        self.horizontalLayout.addWidget(self.lineEdit_NewPath)
        self.pushButton_ChooseNewPath = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_ChooseNewPath.setObjectName("pushButton_ChooseNewPath")
        self.horizontalLayout.addWidget(self.pushButton_ChooseNewPath)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_MapPaths = QtWidgets.QPushButton(Dialog)
        self.pushButton_MapPaths.setObjectName("pushButton_MapPaths")
        self.horizontalLayout_2.addWidget(self.pushButton_MapPaths)
        self.pushButton_Cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout_2.addWidget(self.pushButton_Cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Document File Paths Debugging"))
        self.groupBox.setTitle(_translate("Dialog", "Choose a Path to Map"))
        self.groupBox_3.setTitle(_translate("Dialog", "Old Path"))
        self.groupBox_2.setTitle(_translate("Dialog", "New Path"))
        self.pushButton_ChooseNewPath.setText(_translate("Dialog", "Choose Folder"))
        self.pushButton_MapPaths.setText(_translate("Dialog", "Map Paths"))
        self.pushButton_Cancel.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
