# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout_main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1219, 979)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.pushButton_ProjectSwitch = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ProjectSwitch.sizePolicy().hasHeightForWidth())
        self.pushButton_ProjectSwitch.setSizePolicy(sizePolicy)
        self.pushButton_ProjectSwitch.setFlat(True)
        self.pushButton_ProjectSwitch.setObjectName("pushButton_ProjectSwitch")
        self.horizontalLayout.addWidget(self.pushButton_ProjectSwitch)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(20)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_TaskFrame = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_TaskFrame.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_TaskFrame.setObjectName("verticalLayout_TaskFrame")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_TaskSearch = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_TaskSearch.setObjectName("lineEdit_TaskSearch")
        self.verticalLayout_2.addWidget(self.lineEdit_TaskSearch)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_3.addWidget(self.checkBox_2)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.treeView_Tasks = QtWidgets.QTreeView(self.groupBox)
        self.treeView_Tasks.setObjectName("treeView_Tasks")
        self.verticalLayout_2.addWidget(self.treeView_Tasks)
        self.verticalLayout_TaskFrame.addWidget(self.groupBox)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_DiaryFrame = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_DiaryFrame.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_DiaryFrame.setObjectName("verticalLayout_DiaryFrame")
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_DiarySearch = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_DiarySearch.setObjectName("lineEdit_DiarySearch")
        self.verticalLayout_3.addWidget(self.lineEdit_DiarySearch)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_5.addWidget(self.checkBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_5.addWidget(self.comboBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.tableView_Diary = QtWidgets.QTableView(self.groupBox_2)
        self.tableView_Diary.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_Diary.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableView_Diary.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableView_Diary.setObjectName("tableView_Diary")
        self.tableView_Diary.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tableView_Diary)
        self.verticalLayout_DiaryFrame.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.splitter)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1219, 38))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Project = QtWidgets.QAction(MainWindow)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.actionProject_Settings = QtWidgets.QAction(MainWindow)
        self.actionProject_Settings.setObjectName("actionProject_Settings")
        self.actionNew_Project = QtWidgets.QAction(MainWindow)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.menuFile.addAction(self.actionOpen_Project)
        self.menuFile.addAction(self.actionProject_Settings)
        self.menuFile.addAction(self.actionNew_Project)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Project:"))
        self.pushButton_ProjectSwitch.setText(_translate("MainWindow", "PROJECT_NAME"))
        self.groupBox.setTitle(_translate("MainWindow", "Tasks"))
        self.checkBox_2.setText(_translate("MainWindow", "CheckBox"))
        self.comboBox.setItemText(0, _translate("MainWindow", "All"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Completed"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Uncompleted"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Diary"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_Project.setText(_translate("MainWindow", "Open Project"))
        self.actionProject_Settings.setText(_translate("MainWindow", "Project Settings"))
        self.actionNew_Project.setText(_translate("MainWindow", "New Project"))

